import type { Metadata } from "next";
// import "@app/globals.css";
import "@/css/common.css";

export const metadata: Metadata = {
  title: "海南志途教育科技有限公司",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh" className="overflow-x-hidden">
      <body
        className={`min-w-screen bg-main-bg bg-auto bg-[#f7f7e9] bg-no-repeat bg-bottom`}
      >
        {children}
      </body>
    </html>
  );
}
