import type { Metadata } from "next";
import "./globals.css";
import "@/css/common.css";

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "海南志途教育科技有限公司",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh" className="overflow-x-hidden">
      <body className="min-w-[100vw] min-h-[100vh] bg-main-bg bg-auto bg-[#f7f7e9] bg-no-repeat bg-bottom">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
