import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/css/common.css";

const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "海南志途教育科技有限公司",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh" className="overflow-x-hidden">
      <body
        className={`min-w-screen min-h-screen bg-main-bg bg-auto bg-[#f7f7e9] bg-no-repeat bg-bottom`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
